### ISSUE TITLE
Given two very similiar XML trees, xtdiff provides many many changes

### ISSUE THREAD

**Issue by coler-j** [cfpb/xtdiff#2]
Given a left tree of:

`<xml xmlns="http://www.w3.org/1999/xhtml">
   <variables>
      <variable type="">x</variable>
   </variables>
   <block type="text_print">
      <value name="TEXT">
         <block type="text">
            <field name="TEXT">Hello world</field>
         </block>
      </value>
   </block>
</xml>`

And a right tree of:

`<xml xmlns="http://www.w3.org/1999/xhtml">
   <variables>
      <variable type="">x</variable>
   </variables>
   <block type="text_print">
      <value name="TEXT">
         <block type="text">
            <field name="TEXT">Hello world</field>
         </block>
      </value>
      <next>
         <block type="text_print">
            <value name="TEXT">
               <block type="text">
                  <field name="TEXT">next</field>
               </block>
            </value>
         </block>
      </next>
   </block>
</xml>`

Doing the following provides a mess of a difference. Why?

`left = """<xml xmlns="http://www.w3.org/1999/xhtml"><variables><variable type="">x</variable></variables><block type="text_print"><value name="TEXT"><block type="text"><field name="TEXT">Hello world</field></block></value></block></xml>"""`

`right = """<xml xmlns="http://www.w3.org/1999/xhtml"><variables><variable type="">x</variable></variables><block type="text_print"><value name="TEXT"><block type="text"><field name="TEXT">Hello world</field></block></value><next><block type="text_print"><value name="TEXT"><block type="text"><field name="TEXT">next</field></block></value></block></next></block></xml>"""`

`difference = xtdiff.diff(etree.fromstring(left), etree.fromstring(right))`

The Difference:

`OrderedSet( [INSERT(node=b'<block xmlns="http://www.w3.org/1999/xhtml" type="text_print"><value name="TEXT"><block type="text"><field name="TEXT">Hello world</field></block></value><next><block type="text_print"><value name="TEXT"><block type="text"><field name="TEXT">next</field></block></value></block></next></block>', parent='/*', index=1), MOVE(path='/*/*[3]/*', parent='/*/*[2]', index=0), INSERT(node=b'<next xmlns="http://www.w3.org/1999/xhtml"><block type="text_print"><value name="TEXT"><block type="text"><field name="TEXT">next</field></block></value></block></next>', parent='/*/*[2]', index=1), INSERT(node=b'<block xmlns="http://www.w3.org/1999/xhtml" type="text_print"><value name="TEXT"><block type="text"><field name="TEXT">next</field></block></value></block>', parent='/*/*[2]/*[2]', index=0), INSERT(node=b'<value xmlns="http://www.w3.org/1999/xhtml" name="TEXT"><block type="text"><field name="TEXT">next</field></block></value>', parent='/*/*[2]/*[2]/*', index=0), INSERT(node=b'<block xmlns="http://www.w3.org/1999/xhtml" type="text"><field name="TEXT">next</field></block>', parent='/*/*[2]/*[2]/*/*', index=0),    
    INSERT(node=b'<field xmlns="http://www.w3.org/1999/xhtml" name="TEXT">next</field>', parent='/*/*[2]/*[2]/*/*/*', index=0), DELETE(path='/*/*[3]'), DELETE(path='/*/*[2]/*[4]/*/*/*/*'), DELETE(path='/*/*[2]/*[4]/*/*/*'), DELETE(path='/*/*[2]/*[4]/*/*'), DELETE(path='/*/*[2]/*[4]/*'), DELETE(path='/*/*[2]/*[4]'), DELETE(path='/*/*[2]/*[3]/*/*'), DELETE(path='/*/*[2]/*[3]/*'), DELETE(path='/*/*[2]/*[3]'), DELETE(path='/*/*[2]/*[2]/*[2]/*/*/*'), DELETE(path='/*/*[2]/*[2]/*[2]/*/*'), DELETE(path='/*/*[2]/*[2]/*[2]/*'), DELETE(path='/*/*[2]/*[2]/*[2]'), DELETE(path='/*/*[2]/*[2]/*/*[2]/*/*'), DELETE(path='/*/*[2]/*[2]/*/*[2]/*'), DELETE(path='/*/*[2]/*[2]/*/*[2]'), DELETE(path='/*/*[2]/*[2]/*/*/*[2]/*'), DELETE(path='/*/*[2]/*[2]/*/*/*[2]'), DELETE(path='/*/*[2]/*[2]/*/*/*/*[2]')]
    )`

**Comment by wisotzky** [comment]
For me it shows even dozens of differences, when using exactly the same XML document twice.

**Comment by coler-j** [comment]
Yeah, I removed this lib from my project didn't have time to look into it.
There isn't an alternative lib though.

**Comment by wisotzky** [comment]
@coler-j 
Do you have any recommendation, what python library to use? I want to take a XML configuration snapshot of a device before and after a change. The python library should provide me with a dictionary, containing all the changes (addition, modification, deletion). As this is to be used in context of Ansible - installation should be very simple (e.g. pip).

thx

**Comment by coler-j** [comment]
Unfortunately no. For my current project I was able to get away with just a
string comparison to see if the XML matched. I guess suggestion would be to
dig into this package and see if you can fix it. :(

**Comment by coler-j** [comment]
Project is deprecated so closing this issue.
